import picture1 from "@/assets/icon1.png"
import picture2 from "@/assets/icon2.png"
import picture3 from "@/assets/icons3.png"
import picture4 from "@/assets/icons4.jpeg"

export const mockUsers = [
    {
        id: "1",
        name: "Rahul Sharma",
        email: "rahul.s@example.com",
        phone: "+91 9876543210",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Male",
        userType: "Student (12)",
        profileStage: "Registered",
        assessments: {
            total: 2,
            completed: 1,
        },
        sessions: {
            total: 3,
            missed: 1,
        },
        source: "BA Campaign",
        joinDate: "15 May 2023",
        lastLogin: "17 May 2023",
        status: "Active",
    },
    {
        id: "2",
        name: "Priya Patel",
        email: "priya.p@example.com",
        phone: "+91 9876543211",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Female",
        userType: "Student (10)",
        profileStage: "Enquiry",
        assessments: {
            total: 1,
            completed: 0,
        },
        sessions: {
            total: 1,
            missed: 0,
        },
        source: "Consultant",
        joinDate: "10 May 2023",
        lastLogin: "16 May 2023",
        status: "Active",
    },
    {
        id: "3",
        name: "Amit Kumar",
        email: "amit.k@example.com",
        phone: "+91 9876543212",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Male",
        userType: "Student (UG)",
        profileStage: "Registered",
        assessments: {
            total: 2,
            completed: 2,
        },
        sessions: {
            total: 4,
            missed: 0,
        },
        source: "Organisation",
        joinDate: "5 May 2023",
        lastLogin: "15 May 2023",
        status: "Active",
    },
    {
        id: "4",
        name: "Sneha Gupta",
        email: "sneha.g@example.com",
        phone: "+91 9876543213",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Female",
        userType: "Student (12)",
        profileStage: "Guest",
        assessments: {
            total: 0,
            completed: 0,
        },
        sessions: {
            total: 0,
            missed: 0,
        },
        source: "Organic",
        joinDate: "12 May 2023",
        lastLogin: "12 May 2023",
        status: "Inactive",
    },
    {
        id: "5",
        name: "Vikram Singh",
        email: "vikram.s@example.com",
        phone: "+91 9876543214",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Male",
        userType: "Student (UG)",
        profileStage: "Registered",
        assessments: {
            total: 2,
            completed: 1,
        },
        sessions: {
            total: 2,
            missed: 1,
        },
        source: "BA Campaign",
        joinDate: "8 May 2023",
        lastLogin: "14 May 2023",
        status: "Active",
    },
    {
        id: "6",
        name: "Anjali Mehta",
        email: "anjali.m@example.com",
        phone: "+91 9876543215",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Female",
        userType: "Student (10)",
        profileStage: "Enquiry",
        assessments: {
            total: 1,
            completed: 1,
        },
        sessions: {
            total: 1,
            missed: 0,
        },
        source: "Consultant",
        joinDate: "9 May 2023",
        lastLogin: "10 May 2023",
        status: "Active",
    },
    {
        id: "7",
        name: "Rohit Verma",
        email: "rohit.v@example.com",
        phone: "+91 9876543216",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Male",
        userType: "Student (UG)",
        profileStage: "Registered",
        assessments: {
            total: 3,
            completed: 2,
        },
        sessions: {
            total: 3,
            missed: 1,
        },
        source: "Referral",
        joinDate: "6 May 2023",
        lastLogin: "8 May 2023",
        status: "Active",
    },
    {
        id: "8",
        name: "Kavya Reddy",
        email: "kavya.r@example.com",
        phone: "+91 9876543217",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Female",
        userType: "Student (12)",
        profileStage: "Registered",
        assessments: {
            total: 2,
            completed: 0,
        },
        sessions: {
            total: 2,
            missed: 2,
        },
        source: "Organic",
        joinDate: "7 May 2023",
        lastLogin: "9 May 2023",
        status: "Inactive",
    },
    {
        id: "9",
        name: "Nikhil Joshi",
        email: "nikhil.j@example.com",
        phone: "+91 9876543218",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Male",
        userType: "Student (PG)",
        profileStage: "Enquiry",
        assessments: {
            total: 1,
            completed: 1,
        },
        sessions: {
            total: 1,
            missed: 0,
        },
        source: "Consultant",
        joinDate: "10 May 2023",
        lastLogin: "11 May 2023",
        status: "Active",
    },
    {
        id: "10",
        name: "Meera Nair",
        email: "meera.n@example.com",
        phone: "+91 9876543219",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Female",
        userType: "Student (UG)",
        profileStage: "Registered",
        assessments: {
            total: 3,
            completed: 3,
        },
        sessions: {
            total: 3,
            missed: 0,
        },
        source: "BA Campaign",
        joinDate: "11 May 2023",
        lastLogin: "13 May 2023",
        status: "Active",
    },
    {
        id: "11",
        name: "Siddharth Rao",
        email: "siddharth.r@example.com",
        phone: "+91 9876543220",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Male",
        userType: "Student (12)",
        profileStage: "Guest",
        assessments: {
            total: 0,
            completed: 0,
        },
        sessions: {
            total: 0,
            missed: 0,
        },
        source: "Organisation",
        joinDate: "13 May 2023",
        lastLogin: "13 May 2023",
        status: "Inactive",
    },
    {
        id: "12",
        name: "Pooja Iyer",
        email: "pooja.i@example.com",
        phone: "+91 9876543221",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Female",
        userType: "Student (PG)",
        profileStage: "Registered",
        assessments: {
            total: 2,
            completed: 2,
        },
        sessions: {
            total: 2,
            missed: 0,
        },
        source: "Referral",
        joinDate: "14 May 2023",
        lastLogin: "15 May 2023",
        status: "Active",
    },
    {
        id: "13",
        name: "Arjun Desai",
        email: "arjun.d@example.com",
        phone: "+91 9876543222",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Male",
        userType: "Student (10)",
        profileStage: "Guest",
        assessments: {
            total: 0,
            completed: 0,
        },
        sessions: {
            total: 1,
            missed: 1,
        },
        source: "Organic",
        joinDate: "6 May 2023",
        lastLogin: "6 May 2023",
        status: "Inactive",
    },
    {
        id: "14",
        name: "Neha Bansal",
        email: "neha.b@example.com",
        phone: "+91 9876543223",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Female",
        userType: "Student (UG)",
        profileStage: "Registered",
        assessments: {
            total: 3,
            completed: 1,
        },
        sessions: {
            total: 2,
            missed: 1,
        },
        source: "Consultant",
        joinDate: "4 May 2023",
        lastLogin: "6 May 2023",
        status: "Active",
    },
    {
        id: "15",
        name: "Manish Agarwal",
        email: "manish.a@example.com",
        phone: "+91 9876543224",
        photo: [picture1, picture2, picture3, picture4][Math.floor(Math.random() * 4)],
        gender: "Male",
        userType: "Student (PG)",
        profileStage: "Enquiry",
        assessments: {
            total: 1,
            completed: 0,
        },
        sessions: {
            total: 1,
            missed: 0,
        },
        source: "BA Campaign",
        joinDate: "3 May 2023",
        lastLogin: "5 May 2023",
        status: "Active",
    }
]
